src/components/ArtifactList.tsx, src/components/Environment.tsx, src/components/PackageRow.tsx, src/components/hooks/useGroupedArtifacts.ts, src/types.ts
Was a bit confusing which inputs belong to which environment.
Before:
After:
=> new: Improve package output when multiple environments

src/babel/config.ts, src/rollup/config.ts, tests/__snapshots__/outputs.test.ts.snap, tests/babel/__snapshots__/config.test.ts.snap, tests/rollup/config.test.ts
=> new: Add banner comments for each output file.

package.json, src/babel/config.ts, src/rollup/config.ts, src/schemas.ts, tests/__fixtures__/examples/async-await.ts, tests/__fixtures__/examples/generators.ts, tests/__fixtures__/examples/node-polyfills.ts, tests/__fixtures__/examples/package.json, tests/__snapshots__/outputs.test.ts.snap, tests/babel/__snapshots__/config.test.ts.snap, tests/outputs.test.ts, tests/rollup/config.test.ts, website/docs/build.md, yarn.lock
When platform is browser/native, we should polyfill any Node.js built-in modules.
Solves https://github.com/milesj/packemon/issues/24
Also improved async/await and generator transformation.
=> new: Polyfill node modules for other platforms.

src/Package.ts, src/Packemon.ts, src/rollup/config.ts, src/schemas.ts, src/types.ts, tests/Package.test.ts, tests/Packemon.test.ts, tests/helpers.ts, tests/rollup/config.test.ts, website/docs/config.md, website/docs/pack.md
Implements https://github.com/milesj/packemon/issues/35
=> new: Support a `bundle` config option.

src/Packemon.ts, src/commands/Base.tsx, src/commands/Build.tsx, src/commands/Init.tsx, src/commands/Pack.tsx, src/commands/Watch.tsx, src/helpers/matchesPattern.ts, src/schemas.ts, src/types.ts, tests/Packemon.test.ts, website/docs/build.md
=> new: Add `--filterFormats` option.

src/Packemon.ts, src/commands/Base.tsx, src/commands/Build.tsx, src/commands/Init.tsx, src/commands/Pack.tsx, src/commands/Watch.tsx, src/schemas.ts, src/types.ts, tests/Packemon.test.ts, website/docs/build.md
Implements https://github.com/milesj/packemon/issues/41
=> new: Add `--filterPlatforms` option.

.npmignore, src/CodeArtifact.ts, src/TypesArtifact.ts, src/babel/config.ts, tests/CodeArtifact.test.ts, tests/Package.test.ts, tests/babel/__snapshots__/config.test.ts.snap
Fixes: https://github.com/milesj/packemon/issues/42
=> fix: Improve entry point handling with a ton of inputs.

src/babel/config.ts, src/rollup/config.ts, tests/__snapshots__/outputs.test.ts.snap, tests/babel/__snapshots__/config.test.ts.snap, tests/examples/__snapshots__/asyncAwait.test.ts.snap, tests/examples/__snapshots__/generators.test.ts.snap, tests/examples/__snapshots__/jsonImports.test.ts.snap, tests/examples/__snapshots__/nodePolyfills.test.ts.snap, tests/helpers.ts, tests/rollup/config.test.ts
Now that are supported versions have changed, we can update all these conditionals to better represent our targets.
=> breaking: Adjust Babel and Rollup plugins.

packages/packemon/src/CodeArtifact.ts, packages/packemon/src/Package.ts, packages/packemon/src/Packemon.ts, packages/packemon/src/rollup/config.ts, packages/packemon/src/schemas.ts, packages/packemon/src/types.ts, packages/packemon/tests/Package.test.ts, packages/packemon/tests/Packemon.test.ts, packages/packemon/tests/examples/__snapshots__/externals.test.ts.snap, packages/packemon/tests/examples/externals.test.ts, packages/packemon/tests/helpers.ts, tests/__fixtures__/examples/externals.ts, website/docs/config.md
Allow custom Rollup externals to be defined.
=> new: Support a new `externals` option.

packages/packemon/src/Package.ts, packages/packemon/src/PackageValidator.ts, packages/packemon/src/bin.ts, packages/packemon/src/commands/Files.tsx, packages/packemon/src/components/Files/List.tsx, packages/packemon/src/components/Files/Symbol.tsx, packages/packemon/src/components/Files/Tree.tsx, packages/packemon/src/components/Files/TreeContext.ts, packages/packemon/src/components/Files/index.tsx, packages/packemon/src/index.ts, website/docs/files.md, website/sidebars.js
This can be used to figure out the contents of an npm package before distributing.
=> new: Add a `files` command.

packages/babel-plugin-cjs-esm-interop/package.json, packages/babel-plugin-conditional-invariant/package.json, packages/babel-plugin-env-constants/package.json, packages/packemon/package.json, packages/packemon/src/Artifact.ts, packages/packemon/src/CodeArtifact.ts, packages/packemon/src/Package.ts, packages/packemon/src/Packemon.ts, packages/packemon/src/TypesArtifact.ts, packages/packemon/src/schemas.ts, packages/packemon/src/types.ts, packages/packemon/tests/CodeArtifact.test.ts, packages/packemon/tests/Package.test.ts, packages/packemon/tests/Packemon.test.ts, packages/packemon/tests/TypesArtifact.test.ts, scripts/setup.mjs, website/docs/build.md, website/docs/config.md
You can now declare your package's API, either public or private.
=> new: Add `api` config setting.

packages/packemon/package.json, packages/packemon/src/Package.ts, packages/packemon/src/commands/Build.tsx, packages/packemon/src/commands/Pack.tsx, packages/packemon/src/schemas.ts, packages/packemon/src/types.ts, packages/packemon/tests/Package.test.ts, packages/packemon/tests/Packemon.test.ts, packages/packemon/tests/__snapshots__/outputs.test.ts.snap, website/docs/build.md, website/docs/files.md, website/docs/install.mdx, yarn.lock
A lot of people dislike the automatic inclusion of `files`, so let's wrap it behind an `addFiles` option.
For backwards compat, this defaults to true but will change in the next major.
=> new: Support an `addFiles` option.

packages/packemon/src/babel/config.ts, packages/packemon/tests/babel/__snapshots__/config.test.ts.snap, packages/packemon/tests/examples/__snapshots__/dynamicImports.test.ts.snap, packages/packemon/tests/examples/dynamicImports.test.ts, tests/__fixtures__/examples/dynamic-imports.ts, website/docs/features.md
This logic is now natively built-in.
=> new: Support code-splitting and dynamic imports.

packages/packemon/src/commands/Base.ts, packages/packemon/src/commands/Build.tsx, packages/packemon/src/commands/Files.tsx, packages/packemon/src/commands/Scaffold.tsx, packages/packemon/src/commands/Validate.tsx, packages/packemon/src/components/Build/index.tsx, packages/packemon/src/components/Pack/index.tsx, packages/packemon/src/components/Validate/index.tsx, packages/packemon/src/schemas.ts, packages/packemon/src/types.ts, packages/packemon/tests/Packemon.test.ts
This will reduce the "live" noise but will still output at the end.
=> new: Add a `--quiet` option.

.github/workflows/build.yml, packages/packemon/src/commands/Scaffold.tsx
Just to ensure things haven't broken.
=> ci: Test scaffolding.

package.json, packages/packemon/package.json, packages/packemon/src/babel/config.ts, packages/packemon/src/helpers/shouldKeepDynamicImport.ts, packages/packemon/src/rollup/config.ts, packages/packemon/src/rollup/plugins/preserveDynamicImport.ts, packages/packemon/src/swc/config.ts, packages/packemon/tests/babel/__snapshots__/config.test.ts.snap, packages/packemon/tests/examples/__snapshots__/dynamicImports.test.ts.snap, packages/packemon/tests/rollup/config.test.ts, packages/packemon/tests/swc/__snapshots__/config.test.ts.snap, yarn.lock
Looks like Rollup was transforming these, so had to utilize a custom plugin.
=> fix: Ensure dynamic imports are preserved for the target platform.

.github/workflows/build.yml, packages/packemon/package.json, packages/packemon/src/Package.ts, packages/packemon/src/babel/config.ts, packages/packemon/src/swc/config.ts, packages/packemon/src/types.ts, packages/packemon/tests/Package.test.ts, packages/packemon/tests/babel/__snapshots__/config.test.ts.snap, packages/packemon/tests/babel/config.test.ts, packages/packemon/tests/examples/__snapshots__/solid.test.ts.snap, packages/packemon/tests/examples/solid.test.ts, packages/packemon/tests/helpers.ts, tests/__fixtures__/example-solid/package.json, tests/__fixtures__/example-solid/solid.tsx, tests/__fixtures__/examples/solid.tsx, tests/__fixtures__/workspaces-feature-flags/packages/solid/package.json, website/docs/features.md, website/docs/swc.md, yarn.lock
Unfortunately this doesn't work with swc.
=> new: Add Solid.js support (Babel only).

packages/packemon/src/Package.ts, packages/packemon/tests/Package.test.ts, packages/packemon/tests/__snapshots__/outputs.test.ts.snap
Fixes https://github.com/milesj/packemon/issues/148
=> fix: Use non-index inputs for entry points.

packages/packemon/package.json, packages/packemon/src/bin.ts, packages/packemon/src/commands/Base.ts, yarn.lock
Will just enable the debugger.
=> new: Add global `--debug` flag.

packages/packemon/src/Package.ts, packages/packemon/tests/Package.test.ts
=> fix: Dont validate packages if theres no packemon block.

packages/packemon/src/rollup/plugins/copyAndRefAssets.ts, packages/packemon/tests/__snapshots__/outputs.test.ts.snap, packages/packemon/tests/examples/__snapshots__/assetImports.test.ts.snap, packages/packemon/tests/helpers.ts, packages/packemon/tests/outputs.test.ts
Fixes https://github.com/milesj/packemon/issues/186
=> fix: Fix assets paths not resolving to the correct location.
