milesj/packemon

- .github/workflows/build.yml
- src/Artifact.ts
- src/BundleArtifact.ts
- src/Package.ts
- src/Packemon.ts
- src/TypesArtifact.ts
- src/babel.ts
- src/babel/config.ts
- src/commands/Build.tsx
- src/components/ArtifactRow.tsx
- src/components/Build.tsx
- src/components/Environment.tsx
- src/components/PackageRow.tsx
- src/rollup/config.ts
- src/types.ts
- website/docs/config.md
This allows different platform/format/support combinations per inputs in parallel.
> new: Support multiple configurations per package.

- package.json
- src/BundleArtifact.ts
- src/Package.ts
- src/PackageValidator.ts
- src/Packemon.ts
- src/bin.ts
- src/commands/Build.tsx
- src/commands/Clean.tsx
- src/commands/Pack.tsx
- src/commands/Validate.tsx
- src/components/Build.tsx
- src/components/Pack.tsx
- src/components/PackageList.tsx
- src/components/PackageRow.tsx
- src/components/Validate.tsx
- src/components/ValidateRow.tsx
- src/components/hooks/useOnMount.ts
- src/components/hooks/useRenderLoop.ts
- src/index.ts
- website/docs/build.md
This is a combination of clean + build + validate.
> new: Add `pack` command.

- README.md
- src/BundleArtifact.ts
- src/Package.ts
- src/Packemon.ts
- src/babel.ts
- src/babel/config.ts
- src/components/Environment.tsx
- src/components/Init/PackageForm.tsx
- src/constants.ts
- src/types.ts
- website/docs/config.md
- website/docs/index.md
- website/src/pages/index.tsx
This is rather simple as we only need to target JavaScriptCore (which is what iOS Safari uses).
> new: Add `native` platform to support React Native.

- package.json
- packemon.js
- src/TypesArtifact.ts
- src/babel/config.ts
- src/babel/plugins/envExpressions.ts
- src/types.ts
- website/docs/build.md
Support `__DEV__`, `__PROD__`, and `__TEST__` natively.
> new: Add custom Babel plugin to transform environment expressions.

- package.json
- src/BundleArtifact.ts
- src/Package.ts
- src/Packemon.ts
- src/babel.ts
- src/commands/Watch.tsx
- src/components/ArtifactList.tsx
- src/components/Environment.tsx
- src/components/PackageRow.tsx
- src/components/hooks/useGroupedArtifacts.ts
- src/constants.ts
- src/rollup/config.ts
- src/schemas.ts
- src/types.ts
- tests/BundleArtifact.test.ts
- tests/Package.test.ts
- tests/Packemon.test.ts
- tests/__fixtures__/project-multi-platform/package.json
- tests/rollup/config.test.ts
- types/string-hash.d.ts
- yarn.lock
I've noticed a few edge cases where certain formats weren't being built, or CLI output was missing information. I believe the root is caused by our configs that support multiple platforms, since it requires a bunch of weird resolution logic.
To resolve this, I updated `Package#setConfigs` to create additional configs when platforms is an array. This results in truly unique and deterministic builds.
> fix: Improve bundle build separation.

- package.json
- src/Artifact.ts
- src/BundleArtifact.ts
- src/Package.ts
- src/TypesArtifact.ts
- src/types.ts
- tests/BundleArtifact.test.ts
- tests/Package.test.ts
- tests/TypesArtifact.test.ts
- website/docs/setup.mdx
Because of this PR https://github.com/milesj/packemon/pull/25, automatic entry point's became harder to determine. To resolve this, I moved this logic up to the parent `Package` class, since it has more context.
Also updated `exports` to align more with Webpack/Rollup: https://webpack.js.org/guides/package-exports
> new: Rework automatic entry points and exports.

- src/Artifact.ts
- src/Package.ts
- src/Packemon.ts
- src/rollup/config.ts
- src/schemas.ts
- src/types.ts
- tests/Package.test.ts
- tests/Packemon.test.ts
- tests/__fixtures__/examples/source-maps.ts
- tests/__snapshots__/outputs.test.ts.snap
- tests/outputs.test.ts
- tests/rollup/config.test.ts
- website/docs/build.md
- website/docs/config.md
- website/docs/index.md
Instead of being browser only, is now a setting in the `packemon` config.
> breaking: Move source maps to a config setting.

- .github/workflows/build.yml
- src/constants.ts
- tests/babel/__snapshots__/config.test.ts.snap
- website/docs/config.md
> new: Update experimental target to Node v16.

- package.json
- src/CodeArtifact.ts
- src/Package.ts
- src/babel.ts
- src/commands/Init.tsx
- src/components/Init/PackageForm.tsx
- src/constants.ts
- src/schemas.ts
- tests/Package.test.ts
- tests/Packemon.test.ts
- website/docs/config.md
I want to encourage the use of ECMAScript modules, so Node will now default to `mjs`, and browsers to `esm`.
> breaking: Support ECMAScript as default formats.

- src/Package.ts
- src/components/Init/PackageForm.tsx
- src/constants.ts
- tests/Package.test.ts
- tests/Packemon.test.ts
- website/docs/config.md
While purely ESM would be nice, a lot of tools still don't support it well enough :[
> fix: Bring back `lib` as a browser default format.

- website/docs/setup.mdx
TypeScript requires `declaration: true` when `declarationDir` is used.
For example, when we used next tsconf.json, tsc throw error.( `tsc --init` based and `declarationDir`)
```json
{
"compilerOptions": {
"declarationDir": "dts",
"outDir": "dts",
"target": "ES2018",
"module": "ESNext",
"esModuleInterop": true,
"forceConsistentCasingInFileNames": true,
"strict": true,
"skipLibCheck": true
}
}
```
We got following error.
```bash
$ tsc --noEmit
tsconfig.json:3:5 - error TS5069: Option 'declarationDir' cannot be specified without specifying option 'declaration' or option 'composite'.
3     "declarationDir": "dts",
~~~~~~~~~~~~~~~~
Found 1 error.
```
> docs: Add "declaration" to TypeScript integration.

- packages/packemon/src/CodeArtifact.ts
- packages/packemon/tests/Package.test.ts
This is much cleaner than mapping every file. Also using the inputs here is wrong.
> new: Use subpath patterns for non-bundled exports.

- packages/packemon/package.json
- packages/packemon/src/CodeArtifact.ts
- packages/packemon/src/commands/Build.tsx
- packages/packemon/src/commands/Pack.tsx
- packages/packemon/src/rollup/config.ts
- packages/packemon/src/schemas.ts
- packages/packemon/src/types.ts
- packages/packemon/tests/CodeArtifact.test.ts
- packages/packemon/tests/Packemon.test.ts
- packages/packemon/tests/rollup/config.test.ts
- website/docs/build.md
- website/docs/features.md
- website/docs/migrate/2.0.md
- yarn.lock
This doesn't need to exist in core.
> breaking: Remove `--analyze` option.

- packages/babel-plugin-cjs-esm-interop/package.json
- packages/babel-plugin-conditional-invariant/package.json
- packages/babel-plugin-env-constants/package.json
- packages/packemon/package.json
- packages/packemon/src/CodeArtifact.ts
- packages/packemon/src/Package.ts
- packages/packemon/src/helpers/sortExportConditions.ts
- packages/packemon/src/swc/config.ts
- packages/packemon/src/types.ts
- packages/packemon/tests/examples/react.test.ts
- packages/packemon/tests/helpers/sortExportConditions.test.ts
- packages/packemon/tests/swc/__snapshots__/config.test.ts.snap
- packages/packemon/tests/swc/config.test.ts
With TS 4.7 support `exports` (and `types` condition), we must ensure a correct order since `types` must be first.
> new: Ensure package `exports` conditions are sorted correctly.

- packages/babel-plugin-cjs-esm-interop/package.json
- packages/babel-plugin-conditional-invariant/package.json
- packages/babel-plugin-env-constants/package.json
- packages/packemon/src/CodeArtifact.ts
- packages/packemon/src/Package.ts
- packages/packemon/src/helpers/sortExportConditions.ts
- packages/packemon/src/helpers/sortExports.ts
- packages/packemon/src/types.ts
- packages/packemon/tests/CodeArtifact.test.ts
- packages/packemon/tests/Package.test.ts
We've noticed that browser only builds were failing to find imports in tools like webpack and jest.
I'm assuming it's because the `browser` condition isn't being hit, which in turn doesn't hit `default`. This change bubbles up `default` one level for this to be hit.
> fix: Improve handling of `default` for package exports.

- packages/packemon/src/Package.ts
- packages/packemon/tests/Package.test.ts
Otherwise, we don't know which is the "true" type.
> fix: Only set `type` when there's 1 build.

- package.json
- packages/packemon/src/Package.ts
- packages/packemon/src/TypesArtifact.ts
- packages/packemon/src/commands/Scaffold.tsx
- packages/packemon/src/constants.ts
- packages/packemon/src/types.ts
- packages/packemon/tests/TypesArtifact.test.ts
- packages/packemon/tests/__snapshots__/outputs.test.ts.snap
- packages/packemon/tests/helpers.ts
- packages/packemon/tests/outputs.test.ts
- tests/__fixtures__/project-cts/package.json
- tests/__fixtures__/project-cts/src/index.cts
- tests/__fixtures__/project-cts/tsconfig.json
- tests/__fixtures__/project-mts/package.json
- tests/__fixtures__/project-mts/src/index.mts
- tests/__fixtures__/project-mts/tsconfig.json
- yarn.lock
In turn, this also supports `.d.cts` and `.d.mts` TypeScript declarations.
> new: Support `.cts` and `.mts` files.

- packages/packemon/src/Package.ts
- packages/packemon/tests/Package.test.ts
Instead of overwriting with `Object.assign()`, use a deep merge approach.
> fix: Properly handle package exports for dual formats.

- packages/packemon/src/Package.ts
- packages/packemon/src/Project.ts
- packages/packemon/src/TypesArtifact.ts
- packages/packemon/src/types.ts
- packages/packemon/tests/Package.test.ts
- packages/packemon/tests/Project.test.ts
- packages/packemon/tests/TypesArtifact.test.ts
Declarations will now choose the correct args to use for `tsc` based on the existence of project references or composite options, per project, instead of at the root.
> fix: Update `tsc` to build project references based on the state of the local config.

- packages/packemon/src/Package.ts
- packages/packemon/src/Packemon.ts
- packages/packemon/src/Project.ts
- packages/packemon/src/types.ts
- packages/packemon/tests/Packemon.test.ts
- packages/packemon/tests/configs.test.ts
Packemon is run in 4 different contexts:
- Polyrepo root (builds 1 package)
- Monorepo root (builds all packages)
- Monorepo root with filters (builds N packages)
- Monorepo project (builds 1 package)
The first 3 work just fine, as they were the intended developer flow for Packemon. However, the 4th is currently "broken". Packages build just fine, but configuration (`package.config.js`, etc) are resolved incorrectly, and any `package.json` validation (mainly repository) fails incorrectly.
To solve this problem, I must detect the "repo root".
> fix: Improve workspace root detection. Fix config loading and validation.

- package.json
- packages/packemon/package.json
- packages/packemon/src/PackageValidator.ts
- packages/packemon/src/commands/Files.tsx
- packages/packemon/src/commands/Validate.ts
- packages/packemon/src/schemas.ts
- packages/packemon/src/types.ts
- packages/packemon/tests/PackageValidator.test.ts
- packages/packemon/tests/Packemon.test.ts
- website/docs/migrate/3.0.md
- website/docs/validate.md
- yarn.lock
npm has changed the way `packlist` works, and it's no longer viable.
> breaking: Remove `--files` support from validation.

- packages/packemon/package.json
- packages/packemon/src/Artifact.ts
- packages/packemon/src/Package.ts
- packages/packemon/src/babel/config.ts
- packages/packemon/tests/Artifact.test.ts
- packages/packemon/tests/Package.test.ts
- packages/packemon/tests/babel/__snapshots__/config.test.ts.snap
SolidJS supports a special `solid` package exports, so it can properly handle SSR and non-SSR scenarios. Packemon will now automate the inclusion of this export if Solid has been detected, which will point to the source files.
> new: Support `solid` exports automatically.

- packages/packemon/src/Artifact.ts
- packages/packemon/tests/Package.test.ts
Fixes https://github.com/milesj/packemon/issues/182
> fix: Fix `exports` when configs with different bundle settings are used.

- packages/packemon/src/Artifact.ts
Added on top of https://github.com/milesj/packemon/pull/195 to just add the tsx file support 
https://github.com/milesj/packemon/issues/197
> fix: types not added to export map for tsx input files

- packages/packemon/package.json
- packages/packemon/src/Artifact.ts
- packages/packemon/src/Package.ts
- packages/packemon/src/babel.ts
- packages/packemon/src/babel/config.ts
- packages/packemon/src/rollup/config.ts
- packages/packemon/src/schemas.ts
- packages/packemon/src/swc/config.ts
- packages/packemon/src/types.ts
- packages/packemon/tests/Package.test.ts
- packages/packemon/tests/Packemon.test.ts
- packages/packemon/tests/__snapshots__/outputs.test.ts.snap
- packages/packemon/tests/babel/config.test.ts
- packages/packemon/tests/outputs.test.ts
- packages/packemon/tests/swc/config.test.ts
- tests/__fixtures__/features/package.json
- tests/__fixtures__/features/src/helpers.ts
- website/docs/config.md
- website/docs/swc.md
- yarn.lock
This allows developers to enable swc on a per package basis, as well as control babel/swc helpers.
> new: Support package-level features, starting with `helpers` and `swc`.

- packages/packemon/src/rollup/plugins/copyAndRefAssets.ts
- packages/packemon/tests/rollup/plugins/__fixtures__/src/components/AnotherComponent/anotherEntry.mjs
- packages/packemon/tests/rollup/plugins/__fixtures__/src/components/MyComponent/MySubComponent/bar.mjs
- packages/packemon/tests/rollup/plugins/__fixtures__/src/components/MyComponent/MySubComponent/test.svg
- packages/packemon/tests/rollup/plugins/__fixtures__/src/components/MyComponent/entry.mjs
- packages/packemon/tests/rollup/plugins/copyAndRefAssets.test.ts
There's an issue caused by this line: https://github.com/milesj/packemon/blob/master/packages/packemon/src/rollup/plugins/copyAndRefAssets.ts#L87
chunk.facadeModuleId is not ideal because the bundled code gets moved up to the 
root (output) directory compared to where it was located in the source files, 
the imports in the source files that get bundled get changed to be relative 
to the new bundle location, but the chunk.facadeModuleId is the old location of 
the index. So, you have the old path + the new updated imports and there could be 
overlap due to this "hoisting", which has a workaround in determineNewAsset
There doesn't seem to be a better path to use, so this is a workaround that should hopefully fix this issue. Maybe there is a better way to solve this?
> fix: remove possible overlaps in paths
